name: env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - scikit-learn
  - sqlalchemy
  - mlflow
  - seaborn
  - matplotlib
  - mamba
  - pip
  - pip:
    - transformers
    - python-dotenv