name: env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - sqlalchemy
  - seaborn
  - matplotlib
  - mamba
  - pip
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pip:
      - transformers==4.52.3
      - python-dotenv
      - mlflow
